CREATE DATABASE IF NOT EXISTS chess_game;
USE chess_game;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nickname VARCHAR(50) NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    points INT DEFAULT 0

);